// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package datasource_kubeconfig

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
)

func KubeconfigDataSourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"cluster_ca_certificate": schema.StringAttribute{
				Computed: true,
			},
			"endpoint": schema.StringAttribute{
				Computed:            true,
				Description:         "API endpoint for the cluster",
				MarkdownDescription: "API endpoint for the cluster",
			},
			"force_cert_auth": schema.BoolAttribute{
				Optional:            true,
				Description:         "Force certificate authentication",
				MarkdownDescription: "Force certificate authentication",
			},
			"id": schema.StringAttribute{
				Required:            true,
				Description:         "UUID of the cluster",
				MarkdownDescription: "UUID of the cluster",
			},
			"raw": schema.StringAttribute{
				Computed:            true,
				Description:         "Kubeconfig blob",
				MarkdownDescription: "Kubeconfig blob",
			},
			"token": schema.StringAttribute{
				Computed:            true,
				Description:         "Token to be used from kubeconfig",
				MarkdownDescription: "Token to be used from kubeconfig",
			},
		},
	}
}

type KubeconfigModel struct {
	ClusterCaCertificate types.String `tfsdk:"cluster_ca_certificate"`
	Endpoint             types.String `tfsdk:"endpoint"`
	ForceCertAuth        types.Bool   `tfsdk:"force_cert_auth"`
	Id                   types.String `tfsdk:"id"`
	Raw                  types.String `tfsdk:"raw"`
	Token                types.String `tfsdk:"token"`
}
