// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package resource_cluster

import (
	"context"
	"fmt"
	"github.com/hashicorp/terraform-plugin-framework-validators/int64validator"
	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/booldefault"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/boolplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/int64default"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/int64planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/objectplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringdefault"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-framework/types/basetypes"
	"github.com/hashicorp/terraform-plugin-go/tftypes"
	"regexp"
	"strings"

	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
)

func ClusterResourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"addon_operator_image_tag": schema.StringAttribute{
				Computed: true,
			},
			"allow_workloads_on_master": schema.BoolAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "If the master nodes can run non-critical workloads",
				MarkdownDescription: "If the master nodes can run non-critical workloads",
				PlanModifiers: []planmodifier.Bool{
					boolplanmodifier.UseStateForUnknown(),
					boolplanmodifier.RequiresReplace(),
				},
				Default: booldefault.StaticBool(false),
			},
			"api_server_storage_backend": schema.StringAttribute{
				Computed: true,
			},
			"app_catalog_enabled": schema.BoolAttribute{
				Computed: true,
			},
			"authz_enabled": schema.BoolAttribute{
				Computed: true,
			},
			"calico_controller_cpu_limit": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "Corresponds to the CALICO_CONTROLLER_CPU_LIMIT environment variable in Calico.",
				MarkdownDescription: "Corresponds to the CALICO_CONTROLLER_CPU_LIMIT environment variable in Calico.",
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"calico_controller_memory_limit": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "Corresponds to the CALICO_CONTROLLER_MEMORY_LIMIT environment variable in Calico.",
				MarkdownDescription: "Corresponds to the CALICO_CONTROLLER_MEMORY_LIMIT environment variable in Calico.",
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"calico_ip_ip_mode": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "IP-IP encapsulation mode for Calico network. Choose: Always, Never, CrossSubnet",
				MarkdownDescription: "IP-IP encapsulation mode for Calico network. Choose: Always, Never, CrossSubnet",
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
				Validators: []validator.String{
					stringvalidator.OneOf("Always", "Never", "CrossSubnet"),
				},
				Default: stringdefault.StaticString("Always"),
			},
			"calico_ipv4": schema.StringAttribute{
				Computed: true,
			},
			"calico_ipv4_detection_method": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "Method to detect the IPv4 address",
				MarkdownDescription: "Method to detect the IPv4 address",
				Default:             stringdefault.StaticString("first-found"),
			},
			"calico_ipv6": schema.StringAttribute{
				Computed: true,
			},
			"calico_ipv6_detection_method": schema.StringAttribute{
				Computed: true,
			},
			"calico_ipv6_pool_block_size": schema.StringAttribute{
				Computed: true,
			},
			"calico_ipv6_pool_cidr": schema.StringAttribute{
				Computed: true,
			},
			"calico_ipv6_pool_nat_outgoing": schema.BoolAttribute{
				Computed: true,
			},
			"calico_nat_outgoing": schema.BoolAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "Field is set to true if Calico nodes need to NAT north-south egress traffic.",
				MarkdownDescription: "Field is set to true if Calico nodes need to NAT north-south egress traffic.",
				PlanModifiers: []planmodifier.Bool{
					boolplanmodifier.UseStateForUnknown(),
				},
				Default: booldefault.StaticBool(true),
			},
			"calico_node_cpu_limit": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "Corresponds to the CALICO_NODE_CPU_LIMIT environment variable in Calico.",
				MarkdownDescription: "Corresponds to the CALICO_NODE_CPU_LIMIT environment variable in Calico.",
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"calico_node_memory_limit": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "Corresponds to the CALICO_NODE_MEMORY_LIMIT environment variable in Calico.",
				MarkdownDescription: "Corresponds to the CALICO_NODE_MEMORY_LIMIT environment variable in Calico.",
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"calico_router_id": schema.StringAttribute{
				Computed: true,
			},
			"calico_typha_cpu_limit": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "Corresponds to the CALICO_TYPHA_CPU_LIMIT environment variable in Calico.",
				MarkdownDescription: "Corresponds to the CALICO_TYPHA_CPU_LIMIT environment variable in Calico.",
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"calico_typha_memory_limit": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "Corresponds to the CALICO_TYPHA_MEMORY_LIMIT environment variable in Calico.",
				MarkdownDescription: "Corresponds to the CALICO_TYPHA_MEMORY_LIMIT environment variable in Calico.",
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"calico_v4_block_size": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "Subnet size per node for the Calico network, in CIDR notation (e.g. 26)",
				MarkdownDescription: "Subnet size per node for the Calico network, in CIDR notation (e.g. 26)",
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
				Default: stringdefault.StaticString("26"),
			},
			"can_minor_upgrade": schema.BoolAttribute{
				Computed: true,
			},
			"can_patch_upgrade": schema.BoolAttribute{
				Computed: true,
			},
			"can_upgrade": schema.BoolAttribute{
				Computed:            true,
				Description:         "Can upgrade",
				MarkdownDescription: "Can upgrade",
			},
			"cert_expiry_hrs": schema.Int64Attribute{
				Optional:            true,
				Computed:            true,
				Description:         "Number of hours before user certificates in kubeconfig expires, should be greater than 0 if set",
				MarkdownDescription: "Number of hours before user certificates in kubeconfig expires, should be greater than 0 if set",
				PlanModifiers: []planmodifier.Int64{
					int64planmodifier.UseStateForUnknown(),
				},
				Validators: []validator.Int64{
					int64validator.AtLeast(1),
				},
				Default: int64default.StaticInt64(24),
			},
			"cloud_provider_name": schema.StringAttribute{
				Computed: true,
			},
			"cloud_provider_type": schema.StringAttribute{
				Computed: true,
			},
			"cloud_provider_uuid": schema.StringAttribute{
				Computed: true,
			},
			"container_runtime": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "Container runtime used by this cluster",
				MarkdownDescription: "Container runtime used by this cluster",
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
				Validators: []validator.String{
					stringvalidator.OneOf("containerd"),
				},
				Default: stringdefault.StaticString("containerd"),
			},
			"containers_cidr": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "CIDR used for pod IP addresses, applicable also for manual deploy",
				MarkdownDescription: "CIDR used for pod IP addresses, applicable also for manual deploy",
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
				Default: stringdefault.StaticString("10.20.0.0/16"),
			},
			"cpu_manager_policy": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "options: none, static; default: none",
				MarkdownDescription: "options: none, static; default: none",
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
				Validators: []validator.String{
					stringvalidator.OneOf("none", "static"),
				},
				Default: stringdefault.StaticString("none"),
			},
			"created_at": schema.StringAttribute{
				Computed:            true,
				Description:         "Time at which the cluster was created",
				MarkdownDescription: "Time at which the cluster was created",
			},
			"custom_registry_cert_path": schema.StringAttribute{
				Computed: true,
			},
			"custom_registry_password": schema.StringAttribute{
				Computed: true,
			},
			"custom_registry_repo_path": schema.StringAttribute{
				Computed: true,
			},
			"custom_registry_self_signed_certs": schema.BoolAttribute{
				Computed: true,
			},
			"custom_registry_skip_tls": schema.BoolAttribute{
				Computed: true,
			},
			"custom_registry_url": schema.StringAttribute{
				Computed: true,
			},
			"custom_registry_username": schema.StringAttribute{
				Computed: true,
			},
			"debug": schema.BoolAttribute{
				Computed: true,
			},
			"deploy_kubevirt": schema.BoolAttribute{
				Computed: true,
			},
			"deploy_luigi_operator": schema.BoolAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "If set to true, deploy Luigi operator on the cluster",
				MarkdownDescription: "If set to true, deploy Luigi operator on the cluster",
				PlanModifiers: []planmodifier.Bool{
					boolplanmodifier.UseStateForUnknown(),
				},
				Default: booldefault.StaticBool(false),
			},
			"docker_centos_package_repo_url": schema.StringAttribute{
				Computed: true,
			},
			"docker_private_registry": schema.StringAttribute{
				Computed: true,
			},
			"docker_root": schema.StringAttribute{
				Computed: true,
			},
			"docker_ubuntu_package_repo_url": schema.StringAttribute{
				Computed: true,
			},
			"enable_cas": schema.BoolAttribute{
				Computed: true,
			},
			"enable_catapult_monitoring": schema.BoolAttribute{
				Computed: true,
			},
			"enable_etcd_encryption": schema.BoolAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "Enables etcd encryption",
				MarkdownDescription: "Enables etcd encryption",
				PlanModifiers: []planmodifier.Bool{
					boolplanmodifier.UseStateForUnknown(),
					boolplanmodifier.RequiresReplace(),
				},
				Default: booldefault.StaticBool(true),
			},
			"enable_metallb": schema.BoolAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "If true, install MetalLB to support the loadbalancer service-type",
				MarkdownDescription: "If true, install MetalLB to support the loadbalancer service-type",
				PlanModifiers: []planmodifier.Bool{
					boolplanmodifier.UseStateForUnknown(),
				},
				Default: booldefault.StaticBool(false),
			},
			"etcd_backup": schema.SingleNestedAttribute{
				Attributes: map[string]schema.Attribute{
					"daily_backup_time": schema.StringAttribute{
						Optional:            true,
						Computed:            true,
						Description:         "etcd backup Timestamp for daily backup, specified in format 'HH:MM'",
						MarkdownDescription: "etcd backup Timestamp for daily backup, specified in format 'HH:MM'",
						PlanModifiers: []planmodifier.String{
							stringplanmodifier.UseStateForUnknown(),
						},
						Validators: []validator.String{
							stringvalidator.RegexMatches(regexp.MustCompile(`^(?:[0-1][0-9]|2[0-3]):[0-5][0-9]$`), "Must be a valid time in HH:MM format"),
						},
						Default: stringdefault.StaticString("02:00"),
					},
					"interval_in_hours": schema.Int64Attribute{
						Optional:            true,
						Description:         "etcd backup interval, specified in Hours. intervalInMins and intervalInHours are mutually exclusive",
						MarkdownDescription: "etcd backup interval, specified in Hours. intervalInMins and intervalInHours are mutually exclusive",
						PlanModifiers: []planmodifier.Int64{
							int64planmodifier.UseStateForUnknown(),
						},
						Validators: []validator.Int64{
							int64validator.ConflictsWith(path.MatchRelative().AtName("interval_in_mins")),
							int64validator.AtLeast(1),
						},
					},
					"interval_in_mins": schema.Int64Attribute{
						Optional:            true,
						Description:         "etcd backup interval, specified in minutes. intervalInMins and intervalInHours are mutually exclusive",
						MarkdownDescription: "etcd backup interval, specified in minutes. intervalInMins and intervalInHours are mutually exclusive",
						PlanModifiers: []planmodifier.Int64{
							int64planmodifier.UseStateForUnknown(),
						},
						Validators: []validator.Int64{
							int64validator.AtLeast(1),
						},
					},
					"is_etcd_backup_enabled": schema.BoolAttribute{
						Required:            true,
						Description:         "Set to true if etcd backup should be enabled, false otherwise",
						MarkdownDescription: "Set to true if etcd backup should be enabled, false otherwise",
						PlanModifiers: []planmodifier.Bool{
							boolplanmodifier.UseStateForUnknown(),
						},
					},
					"max_interval_backup_count": schema.Int64Attribute{
						Optional:            true,
						Computed:            true,
						Description:         "max number of Backups retention for interval type backups, required if intervalInMins or intervalInHours is provided",
						MarkdownDescription: "max number of Backups retention for interval type backups, required if intervalInMins or intervalInHours is provided",
						PlanModifiers: []planmodifier.Int64{
							int64planmodifier.UseStateForUnknown(),
						},
						Validators: []validator.Int64{
							int64validator.AtLeast(1),
						},
						Default: int64default.StaticInt64(3),
					},
					"max_timestamp_backup_count": schema.Int64Attribute{
						Optional:            true,
						Computed:            true,
						Description:         "max number of Backups retention for Timestamp type backups, required if dailyBackupTime is provided",
						MarkdownDescription: "max number of Backups retention for Timestamp type backups, required if dailyBackupTime is provided",
						PlanModifiers: []planmodifier.Int64{
							int64planmodifier.UseStateForUnknown(),
						},
						Validators: []validator.Int64{
							int64validator.AtLeast(1),
						},
						Default: int64default.StaticInt64(3),
					},
					"storage_local_path": schema.StringAttribute{
						Optional:            true,
						Computed:            true,
						Description:         "Path on the local filesystem where the etcd backup should be stored. For 'local' storage type only.",
						MarkdownDescription: "Path on the local filesystem where the etcd backup should be stored. For 'local' storage type only.",
						PlanModifiers: []planmodifier.String{
							stringplanmodifier.UseStateForUnknown(),
						},
						Default: stringdefault.StaticString("/etc/pf9/etcd-backup"),
					},
					"storage_type": schema.StringAttribute{
						Optional:            true,
						Computed:            true,
						Description:         "Storage type for the etcd backup. Only 'local' is current supported type. 'local' saves backup to the node's local disk",
						MarkdownDescription: "Storage type for the etcd backup. Only 'local' is current supported type. 'local' saves backup to the node's local disk",
						PlanModifiers: []planmodifier.String{
							stringplanmodifier.UseStateForUnknown(),
						},
						Validators: []validator.String{
							stringvalidator.OneOf("local"),
						},
						Default: stringdefault.StaticString("local"),
					},
				},
				CustomType: EtcdBackupType{
					ObjectType: types.ObjectType{
						AttrTypes: EtcdBackupValue{}.AttributeTypes(ctx),
					},
				},
				Required: true,
				PlanModifiers: []planmodifier.Object{
					objectplanmodifier.UseStateForUnknown(),
				},
			},
			"etcd_data_dir": schema.StringAttribute{
				Computed: true,
			},
			"etcd_election_timeout_ms": schema.Int64Attribute{
				Computed: true,
			},
			"etcd_heartbeat_interval_ms": schema.Int64Attribute{
				Computed: true,
			},
			"etcd_version": schema.StringAttribute{
				Computed: true,
			},
			"external_dns_name": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "Optional DNS name for API endpoint. This field is autogenerated when usePf9Domain is set, also applicable for manual deploy",
				MarkdownDescription: "Optional DNS name for API endpoint. This field is autogenerated when usePf9Domain is set, also applicable for manual deploy",
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"felix_ipv6_support": schema.BoolAttribute{
				Computed: true,
			},
			"flannel_iface_label": schema.StringAttribute{
				Computed: true,
			},
			"flannel_public_iface_label": schema.StringAttribute{
				Computed: true,
			},
			"gcr_private_registry": schema.StringAttribute{
				Computed: true,
			},
			"id": schema.StringAttribute{
				Computed:            true,
				Description:         "UUID of the cluster",
				MarkdownDescription: "UUID of the cluster",
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"interface_detection_method": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "Method to detect the interface",
				MarkdownDescription: "Method to detect the interface",
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"interface_name": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "Name of the interface",
				MarkdownDescription: "Name of the interface",
				Default:             stringdefault.StaticString(""),
			},
			"interface_reachable_ip": schema.StringAttribute{
				Computed: true,
			},
			"ipv6": schema.BoolAttribute{
				Computed: true,
			},
			"is_air_gapped": schema.BoolAttribute{
				Computed: true,
			},
			"is_kubernetes": schema.BoolAttribute{
				Computed: true,
			},
			"is_mesos": schema.BoolAttribute{
				Computed: true,
			},
			"is_swarm": schema.BoolAttribute{
				Computed: true,
			},
			"k8s_api_port": schema.StringAttribute{
				Computed: true,
			},
			"k8s_private_registry": schema.StringAttribute{
				Computed: true,
			},
			"keystone_enabled": schema.BoolAttribute{
				Computed: true,
			},
			"kube_proxy_mode": schema.StringAttribute{
				Computed: true,
			},
			"kube_role_version": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "kube role version to be used when bringing up the cluster.",
				MarkdownDescription: "kube role version to be used when bringing up the cluster.",
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
					stringplanmodifier.RequiresReplace(),
				},
			},
			"last_ok": schema.StringAttribute{
				Computed: true,
			},
			"last_op": schema.StringAttribute{
				Computed: true,
			},
			"master_ip": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "IP of master node",
				MarkdownDescription: "IP of master node",
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"master_nodes": schema.SetAttribute{
				ElementType:         types.StringType,
				Required:            true,
				Description:         "List of uuid of master nodes",
				MarkdownDescription: "List of uuid of master nodes",
			},
			"master_status": schema.StringAttribute{
				Computed: true,
			},
			"master_vip_iface": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "If masterVipIpv4 is specified, this field is required. Specify the interface that the VIP attaches to",
				MarkdownDescription: "If masterVipIpv4 is specified, this field is required. Specify the interface that the VIP attaches to",
			},
			"master_vip_ipv4": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "API server Virtual IP that provides failover. When specified, deploy keepalived setup to cluster master nodes together",
				MarkdownDescription: "API server Virtual IP that provides failover. When specified, deploy keepalived setup to cluster master nodes together",
			},
			"master_vip_vrouter_id": schema.StringAttribute{
				Computed: true,
			},
			"masterless": schema.BoolAttribute{
				Computed: true,
			},
			"metallb_cidr": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "Comma-separated pools of IPs that MetalLB will manage (for example: A.B.C.D-E.F.G.H, I.J.K.L-M.N.O.P)",
				MarkdownDescription: "Comma-separated pools of IPs that MetalLB will manage (for example: A.B.C.D-E.F.G.H, I.J.K.L-M.N.O.P)",
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
				Validators: []validator.String{
					stringvalidator.AlsoRequires(path.MatchRelative().AtName("enable_metallb")),
				},
			},
			"mtu_size": schema.Int64Attribute{
				Optional:            true,
				Computed:            true,
				Description:         "MTU for container network interfaces. Optional and used for the Calico network backend",
				MarkdownDescription: "MTU for container network interfaces. Optional and used for the Calico network backend",
				PlanModifiers: []planmodifier.Int64{
					int64planmodifier.UseStateForUnknown(),
				},
				Default: int64default.StaticInt64(1440),
			},
			"name": schema.StringAttribute{
				Required:            true,
				Description:         "Name of the cluster, applicable also for manual deploy",
				MarkdownDescription: "Name of the cluster, applicable also for manual deploy",
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.RequiresReplace(),
				},
			},
			"network_plugin": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "Network backend to use for container networking. Defaults to flannel. Supported choices are flannel, calico",
				MarkdownDescription: "Network backend to use for container networking. Defaults to flannel. Supported choices are flannel, calico",
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
				Validators: []validator.String{
					stringvalidator.OneOf("calico", "flannel"),
				},
				Default: stringdefault.StaticString("calico"),
			},
			"node_pool_name": schema.StringAttribute{
				Computed: true,
			},
			"node_pool_uuid": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "Optional. UUID of the node pool used for the cluster. Defaults to the first node pool of the local cloud provider type",
				MarkdownDescription: "Optional. UUID of the node pool used for the cluster. Defaults to the first node pool of the local cloud provider type",
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"num_masters": schema.Int64Attribute{
				Computed: true,
			},
			"num_max_workers": schema.Int64Attribute{
				Computed: true,
			},
			"num_min_workers": schema.Int64Attribute{
				Computed: true,
			},
			"num_workers": schema.Int64Attribute{
				Computed: true,
			},
			"patch_upgrade_role_version": schema.StringAttribute{
				Computed: true,
			},
			"privileged": schema.BoolAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "True if cluster runs privileged containers",
				MarkdownDescription: "True if cluster runs privileged containers",
				PlanModifiers: []planmodifier.Bool{
					boolplanmodifier.UseStateForUnknown(),
				},
				Default: booldefault.StaticBool(true),
			},
			"project_id": schema.StringAttribute{
				Computed: true,
			},
			"quay_private_registry": schema.StringAttribute{
				Computed: true,
			},
			"reserved_cpus": schema.StringAttribute{
				Computed: true,
			},
			"runtime_config": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "Applicable also for manual deploy",
				MarkdownDescription: "Applicable also for manual deploy",
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"services_cidr": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "CIDR used for service IP addresses, applicable also for manual deploy",
				MarkdownDescription: "CIDR used for service IP addresses, applicable also for manual deploy",
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
				Default: stringdefault.StaticString("10.21.0.0/16"),
			},
			"status": schema.StringAttribute{
				Computed: true,
			},
			"tags": schema.MapAttribute{
				ElementType:         types.StringType,
				Optional:            true,
				Description:         "User defined key-value pairs represented as a JSON object",
				MarkdownDescription: "User defined key-value pairs represented as a JSON object",
			},
			"task_error": schema.StringAttribute{
				Computed: true,
			},
			"task_status": schema.StringAttribute{
				Computed: true,
			},
			"topology_manager_policy": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "options: none, best-effort, restricted, single-numa-node; default: none",
				MarkdownDescription: "options: none, best-effort, restricted, single-numa-node; default: none",
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
				Validators: []validator.String{
					stringvalidator.OneOf("none", "best-effort", "restricted", "single-numa-node"),
				},
				Default: stringdefault.StaticString("none"),
			},
			"upgrading_to": schema.StringAttribute{
				Computed: true,
			},
			"use_hostname": schema.BoolAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "If set to true nodes will be registered in the cluster using hostname instead of IP address. This option is only applicable to IPv4 hosts.",
				MarkdownDescription: "If set to true nodes will be registered in the cluster using hostname instead of IP address. This option is only applicable to IPv4 hosts.",
				PlanModifiers: []planmodifier.Bool{
					boolplanmodifier.UseStateForUnknown(),
				},
				Default: booldefault.StaticBool(false),
			},
			"worker_nodes": schema.SetAttribute{
				ElementType:         types.StringType,
				Required:            true,
				Description:         "List of uuid of worker nodes",
				MarkdownDescription: "List of uuid of worker nodes",
			},
			"worker_status": schema.StringAttribute{
				Computed: true,
			},
		},
	}
}

type ClusterModel struct {
	AddonOperatorImageTag         types.String    `tfsdk:"addon_operator_image_tag"`
	AllowWorkloadsOnMaster        types.Bool      `tfsdk:"allow_workloads_on_master"`
	ApiServerStorageBackend       types.String    `tfsdk:"api_server_storage_backend"`
	AppCatalogEnabled             types.Bool      `tfsdk:"app_catalog_enabled"`
	AuthzEnabled                  types.Bool      `tfsdk:"authz_enabled"`
	CalicoControllerCpuLimit      types.String    `tfsdk:"calico_controller_cpu_limit"`
	CalicoControllerMemoryLimit   types.String    `tfsdk:"calico_controller_memory_limit"`
	CalicoIpIpMode                types.String    `tfsdk:"calico_ip_ip_mode"`
	CalicoIpv4                    types.String    `tfsdk:"calico_ipv4"`
	CalicoIpv4DetectionMethod     types.String    `tfsdk:"calico_ipv4_detection_method"`
	CalicoIpv6                    types.String    `tfsdk:"calico_ipv6"`
	CalicoIpv6DetectionMethod     types.String    `tfsdk:"calico_ipv6_detection_method"`
	CalicoIpv6PoolBlockSize       types.String    `tfsdk:"calico_ipv6_pool_block_size"`
	CalicoIpv6PoolCidr            types.String    `tfsdk:"calico_ipv6_pool_cidr"`
	CalicoIpv6PoolNatOutgoing     types.Bool      `tfsdk:"calico_ipv6_pool_nat_outgoing"`
	CalicoNatOutgoing             types.Bool      `tfsdk:"calico_nat_outgoing"`
	CalicoNodeCpuLimit            types.String    `tfsdk:"calico_node_cpu_limit"`
	CalicoNodeMemoryLimit         types.String    `tfsdk:"calico_node_memory_limit"`
	CalicoRouterId                types.String    `tfsdk:"calico_router_id"`
	CalicoTyphaCpuLimit           types.String    `tfsdk:"calico_typha_cpu_limit"`
	CalicoTyphaMemoryLimit        types.String    `tfsdk:"calico_typha_memory_limit"`
	CalicoV4BlockSize             types.String    `tfsdk:"calico_v4_block_size"`
	CanMinorUpgrade               types.Bool      `tfsdk:"can_minor_upgrade"`
	CanPatchUpgrade               types.Bool      `tfsdk:"can_patch_upgrade"`
	CanUpgrade                    types.Bool      `tfsdk:"can_upgrade"`
	CertExpiryHrs                 types.Int64     `tfsdk:"cert_expiry_hrs"`
	CloudProviderName             types.String    `tfsdk:"cloud_provider_name"`
	CloudProviderType             types.String    `tfsdk:"cloud_provider_type"`
	CloudProviderUuid             types.String    `tfsdk:"cloud_provider_uuid"`
	ContainerRuntime              types.String    `tfsdk:"container_runtime"`
	ContainersCidr                types.String    `tfsdk:"containers_cidr"`
	CpuManagerPolicy              types.String    `tfsdk:"cpu_manager_policy"`
	CreatedAt                     types.String    `tfsdk:"created_at"`
	CustomRegistryCertPath        types.String    `tfsdk:"custom_registry_cert_path"`
	CustomRegistryPassword        types.String    `tfsdk:"custom_registry_password"`
	CustomRegistryRepoPath        types.String    `tfsdk:"custom_registry_repo_path"`
	CustomRegistrySelfSignedCerts types.Bool      `tfsdk:"custom_registry_self_signed_certs"`
	CustomRegistrySkipTls         types.Bool      `tfsdk:"custom_registry_skip_tls"`
	CustomRegistryUrl             types.String    `tfsdk:"custom_registry_url"`
	CustomRegistryUsername        types.String    `tfsdk:"custom_registry_username"`
	Debug                         types.Bool      `tfsdk:"debug"`
	DeployKubevirt                types.Bool      `tfsdk:"deploy_kubevirt"`
	DeployLuigiOperator           types.Bool      `tfsdk:"deploy_luigi_operator"`
	DockerCentosPackageRepoUrl    types.String    `tfsdk:"docker_centos_package_repo_url"`
	DockerPrivateRegistry         types.String    `tfsdk:"docker_private_registry"`
	DockerRoot                    types.String    `tfsdk:"docker_root"`
	DockerUbuntuPackageRepoUrl    types.String    `tfsdk:"docker_ubuntu_package_repo_url"`
	EnableCas                     types.Bool      `tfsdk:"enable_cas"`
	EnableCatapultMonitoring      types.Bool      `tfsdk:"enable_catapult_monitoring"`
	EnableEtcdEncryption          types.Bool      `tfsdk:"enable_etcd_encryption"`
	EnableMetallb                 types.Bool      `tfsdk:"enable_metallb"`
	EtcdBackup                    EtcdBackupValue `tfsdk:"etcd_backup"`
	EtcdDataDir                   types.String    `tfsdk:"etcd_data_dir"`
	EtcdElectionTimeoutMs         types.Int64     `tfsdk:"etcd_election_timeout_ms"`
	EtcdHeartbeatIntervalMs       types.Int64     `tfsdk:"etcd_heartbeat_interval_ms"`
	EtcdVersion                   types.String    `tfsdk:"etcd_version"`
	ExternalDnsName               types.String    `tfsdk:"external_dns_name"`
	FelixIpv6Support              types.Bool      `tfsdk:"felix_ipv6_support"`
	FlannelIfaceLabel             types.String    `tfsdk:"flannel_iface_label"`
	FlannelPublicIfaceLabel       types.String    `tfsdk:"flannel_public_iface_label"`
	GcrPrivateRegistry            types.String    `tfsdk:"gcr_private_registry"`
	Id                            types.String    `tfsdk:"id"`
	InterfaceDetectionMethod      types.String    `tfsdk:"interface_detection_method"`
	InterfaceName                 types.String    `tfsdk:"interface_name"`
	InterfaceReachableIp          types.String    `tfsdk:"interface_reachable_ip"`
	Ipv6                          types.Bool      `tfsdk:"ipv6"`
	IsAirGapped                   types.Bool      `tfsdk:"is_air_gapped"`
	IsKubernetes                  types.Bool      `tfsdk:"is_kubernetes"`
	IsMesos                       types.Bool      `tfsdk:"is_mesos"`
	IsSwarm                       types.Bool      `tfsdk:"is_swarm"`
	K8sApiPort                    types.String    `tfsdk:"k8s_api_port"`
	K8sPrivateRegistry            types.String    `tfsdk:"k8s_private_registry"`
	KeystoneEnabled               types.Bool      `tfsdk:"keystone_enabled"`
	KubeProxyMode                 types.String    `tfsdk:"kube_proxy_mode"`
	KubeRoleVersion               types.String    `tfsdk:"kube_role_version"`
	LastOk                        types.String    `tfsdk:"last_ok"`
	LastOp                        types.String    `tfsdk:"last_op"`
	MasterIp                      types.String    `tfsdk:"master_ip"`
	MasterNodes                   types.Set       `tfsdk:"master_nodes"`
	MasterStatus                  types.String    `tfsdk:"master_status"`
	MasterVipIface                types.String    `tfsdk:"master_vip_iface"`
	MasterVipIpv4                 types.String    `tfsdk:"master_vip_ipv4"`
	MasterVipVrouterId            types.String    `tfsdk:"master_vip_vrouter_id"`
	Masterless                    types.Bool      `tfsdk:"masterless"`
	MetallbCidr                   types.String    `tfsdk:"metallb_cidr"`
	MtuSize                       types.Int64     `tfsdk:"mtu_size"`
	Name                          types.String    `tfsdk:"name"`
	NetworkPlugin                 types.String    `tfsdk:"network_plugin"`
	NodePoolName                  types.String    `tfsdk:"node_pool_name"`
	NodePoolUuid                  types.String    `tfsdk:"node_pool_uuid"`
	NumMasters                    types.Int64     `tfsdk:"num_masters"`
	NumMaxWorkers                 types.Int64     `tfsdk:"num_max_workers"`
	NumMinWorkers                 types.Int64     `tfsdk:"num_min_workers"`
	NumWorkers                    types.Int64     `tfsdk:"num_workers"`
	PatchUpgradeRoleVersion       types.String    `tfsdk:"patch_upgrade_role_version"`
	Privileged                    types.Bool      `tfsdk:"privileged"`
	ProjectId                     types.String    `tfsdk:"project_id"`
	QuayPrivateRegistry           types.String    `tfsdk:"quay_private_registry"`
	ReservedCpus                  types.String    `tfsdk:"reserved_cpus"`
	RuntimeConfig                 types.String    `tfsdk:"runtime_config"`
	ServicesCidr                  types.String    `tfsdk:"services_cidr"`
	Status                        types.String    `tfsdk:"status"`
	Tags                          types.Map       `tfsdk:"tags"`
	TaskError                     types.String    `tfsdk:"task_error"`
	TaskStatus                    types.String    `tfsdk:"task_status"`
	TopologyManagerPolicy         types.String    `tfsdk:"topology_manager_policy"`
	UpgradingTo                   types.String    `tfsdk:"upgrading_to"`
	UseHostname                   types.Bool      `tfsdk:"use_hostname"`
	WorkerNodes                   types.Set       `tfsdk:"worker_nodes"`
	WorkerStatus                  types.String    `tfsdk:"worker_status"`
}

var _ basetypes.ObjectTypable = EtcdBackupType{}

type EtcdBackupType struct {
	basetypes.ObjectType
}

func (t EtcdBackupType) Equal(o attr.Type) bool {
	other, ok := o.(EtcdBackupType)

	if !ok {
		return false
	}

	return t.ObjectType.Equal(other.ObjectType)
}

func (t EtcdBackupType) String() string {
	return "EtcdBackupType"
}

func (t EtcdBackupType) ValueFromObject(ctx context.Context, in basetypes.ObjectValue) (basetypes.ObjectValuable, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributes := in.Attributes()

	dailyBackupTimeAttribute, ok := attributes["daily_backup_time"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`daily_backup_time is missing from object`)

		return nil, diags
	}

	dailyBackupTimeVal, ok := dailyBackupTimeAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`daily_backup_time expected to be basetypes.StringValue, was: %T`, dailyBackupTimeAttribute))
	}

	intervalInHoursAttribute, ok := attributes["interval_in_hours"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`interval_in_hours is missing from object`)

		return nil, diags
	}

	intervalInHoursVal, ok := intervalInHoursAttribute.(basetypes.Int64Value)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`interval_in_hours expected to be basetypes.Int64Value, was: %T`, intervalInHoursAttribute))
	}

	intervalInMinsAttribute, ok := attributes["interval_in_mins"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`interval_in_mins is missing from object`)

		return nil, diags
	}

	intervalInMinsVal, ok := intervalInMinsAttribute.(basetypes.Int64Value)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`interval_in_mins expected to be basetypes.Int64Value, was: %T`, intervalInMinsAttribute))
	}

	isEtcdBackupEnabledAttribute, ok := attributes["is_etcd_backup_enabled"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`is_etcd_backup_enabled is missing from object`)

		return nil, diags
	}

	isEtcdBackupEnabledVal, ok := isEtcdBackupEnabledAttribute.(basetypes.BoolValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`is_etcd_backup_enabled expected to be basetypes.BoolValue, was: %T`, isEtcdBackupEnabledAttribute))
	}

	maxIntervalBackupCountAttribute, ok := attributes["max_interval_backup_count"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`max_interval_backup_count is missing from object`)

		return nil, diags
	}

	maxIntervalBackupCountVal, ok := maxIntervalBackupCountAttribute.(basetypes.Int64Value)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`max_interval_backup_count expected to be basetypes.Int64Value, was: %T`, maxIntervalBackupCountAttribute))
	}

	maxTimestampBackupCountAttribute, ok := attributes["max_timestamp_backup_count"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`max_timestamp_backup_count is missing from object`)

		return nil, diags
	}

	maxTimestampBackupCountVal, ok := maxTimestampBackupCountAttribute.(basetypes.Int64Value)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`max_timestamp_backup_count expected to be basetypes.Int64Value, was: %T`, maxTimestampBackupCountAttribute))
	}

	storageLocalPathAttribute, ok := attributes["storage_local_path"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`storage_local_path is missing from object`)

		return nil, diags
	}

	storageLocalPathVal, ok := storageLocalPathAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`storage_local_path expected to be basetypes.StringValue, was: %T`, storageLocalPathAttribute))
	}

	storageTypeAttribute, ok := attributes["storage_type"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`storage_type is missing from object`)

		return nil, diags
	}

	storageTypeVal, ok := storageTypeAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`storage_type expected to be basetypes.StringValue, was: %T`, storageTypeAttribute))
	}

	if diags.HasError() {
		return nil, diags
	}

	return EtcdBackupValue{
		DailyBackupTime:         dailyBackupTimeVal,
		IntervalInHours:         intervalInHoursVal,
		IntervalInMins:          intervalInMinsVal,
		IsEtcdBackupEnabled:     isEtcdBackupEnabledVal,
		MaxIntervalBackupCount:  maxIntervalBackupCountVal,
		MaxTimestampBackupCount: maxTimestampBackupCountVal,
		StorageLocalPath:        storageLocalPathVal,
		StorageType:             storageTypeVal,
		state:                   attr.ValueStateKnown,
	}, diags
}

func NewEtcdBackupValueNull() EtcdBackupValue {
	return EtcdBackupValue{
		state: attr.ValueStateNull,
	}
}

func NewEtcdBackupValueUnknown() EtcdBackupValue {
	return EtcdBackupValue{
		state: attr.ValueStateUnknown,
	}
}

func NewEtcdBackupValue(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) (EtcdBackupValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	// Reference: https://github.com/hashicorp/terraform-plugin-framework/issues/521
	ctx := context.Background()

	for name, attributeType := range attributeTypes {
		attribute, ok := attributes[name]

		if !ok {
			diags.AddError(
				"Missing EtcdBackupValue Attribute Value",
				"While creating a EtcdBackupValue value, a missing attribute value was detected. "+
					"A EtcdBackupValue must contain values for all attributes, even if null or unknown. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("EtcdBackupValue Attribute Name (%s) Expected Type: %s", name, attributeType.String()),
			)

			continue
		}

		if !attributeType.Equal(attribute.Type(ctx)) {
			diags.AddError(
				"Invalid EtcdBackupValue Attribute Type",
				"While creating a EtcdBackupValue value, an invalid attribute value was detected. "+
					"A EtcdBackupValue must use a matching attribute type for the value. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("EtcdBackupValue Attribute Name (%s) Expected Type: %s\n", name, attributeType.String())+
					fmt.Sprintf("EtcdBackupValue Attribute Name (%s) Given Type: %s", name, attribute.Type(ctx)),
			)
		}
	}

	for name := range attributes {
		_, ok := attributeTypes[name]

		if !ok {
			diags.AddError(
				"Extra EtcdBackupValue Attribute Value",
				"While creating a EtcdBackupValue value, an extra attribute value was detected. "+
					"A EtcdBackupValue must not contain values beyond the expected attribute types. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("Extra EtcdBackupValue Attribute Name: %s", name),
			)
		}
	}

	if diags.HasError() {
		return NewEtcdBackupValueUnknown(), diags
	}

	dailyBackupTimeAttribute, ok := attributes["daily_backup_time"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`daily_backup_time is missing from object`)

		return NewEtcdBackupValueUnknown(), diags
	}

	dailyBackupTimeVal, ok := dailyBackupTimeAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`daily_backup_time expected to be basetypes.StringValue, was: %T`, dailyBackupTimeAttribute))
	}

	intervalInHoursAttribute, ok := attributes["interval_in_hours"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`interval_in_hours is missing from object`)

		return NewEtcdBackupValueUnknown(), diags
	}

	intervalInHoursVal, ok := intervalInHoursAttribute.(basetypes.Int64Value)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`interval_in_hours expected to be basetypes.Int64Value, was: %T`, intervalInHoursAttribute))
	}

	intervalInMinsAttribute, ok := attributes["interval_in_mins"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`interval_in_mins is missing from object`)

		return NewEtcdBackupValueUnknown(), diags
	}

	intervalInMinsVal, ok := intervalInMinsAttribute.(basetypes.Int64Value)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`interval_in_mins expected to be basetypes.Int64Value, was: %T`, intervalInMinsAttribute))
	}

	isEtcdBackupEnabledAttribute, ok := attributes["is_etcd_backup_enabled"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`is_etcd_backup_enabled is missing from object`)

		return NewEtcdBackupValueUnknown(), diags
	}

	isEtcdBackupEnabledVal, ok := isEtcdBackupEnabledAttribute.(basetypes.BoolValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`is_etcd_backup_enabled expected to be basetypes.BoolValue, was: %T`, isEtcdBackupEnabledAttribute))
	}

	maxIntervalBackupCountAttribute, ok := attributes["max_interval_backup_count"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`max_interval_backup_count is missing from object`)

		return NewEtcdBackupValueUnknown(), diags
	}

	maxIntervalBackupCountVal, ok := maxIntervalBackupCountAttribute.(basetypes.Int64Value)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`max_interval_backup_count expected to be basetypes.Int64Value, was: %T`, maxIntervalBackupCountAttribute))
	}

	maxTimestampBackupCountAttribute, ok := attributes["max_timestamp_backup_count"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`max_timestamp_backup_count is missing from object`)

		return NewEtcdBackupValueUnknown(), diags
	}

	maxTimestampBackupCountVal, ok := maxTimestampBackupCountAttribute.(basetypes.Int64Value)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`max_timestamp_backup_count expected to be basetypes.Int64Value, was: %T`, maxTimestampBackupCountAttribute))
	}

	storageLocalPathAttribute, ok := attributes["storage_local_path"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`storage_local_path is missing from object`)

		return NewEtcdBackupValueUnknown(), diags
	}

	storageLocalPathVal, ok := storageLocalPathAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`storage_local_path expected to be basetypes.StringValue, was: %T`, storageLocalPathAttribute))
	}

	storageTypeAttribute, ok := attributes["storage_type"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`storage_type is missing from object`)

		return NewEtcdBackupValueUnknown(), diags
	}

	storageTypeVal, ok := storageTypeAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`storage_type expected to be basetypes.StringValue, was: %T`, storageTypeAttribute))
	}

	if diags.HasError() {
		return NewEtcdBackupValueUnknown(), diags
	}

	return EtcdBackupValue{
		DailyBackupTime:         dailyBackupTimeVal,
		IntervalInHours:         intervalInHoursVal,
		IntervalInMins:          intervalInMinsVal,
		IsEtcdBackupEnabled:     isEtcdBackupEnabledVal,
		MaxIntervalBackupCount:  maxIntervalBackupCountVal,
		MaxTimestampBackupCount: maxTimestampBackupCountVal,
		StorageLocalPath:        storageLocalPathVal,
		StorageType:             storageTypeVal,
		state:                   attr.ValueStateKnown,
	}, diags
}

func NewEtcdBackupValueMust(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) EtcdBackupValue {
	object, diags := NewEtcdBackupValue(attributeTypes, attributes)

	if diags.HasError() {
		// This could potentially be added to the diag package.
		diagsStrings := make([]string, 0, len(diags))

		for _, diagnostic := range diags {
			diagsStrings = append(diagsStrings, fmt.Sprintf(
				"%s | %s | %s",
				diagnostic.Severity(),
				diagnostic.Summary(),
				diagnostic.Detail()))
		}

		panic("NewEtcdBackupValueMust received error(s): " + strings.Join(diagsStrings, "\n"))
	}

	return object
}

func (t EtcdBackupType) ValueFromTerraform(ctx context.Context, in tftypes.Value) (attr.Value, error) {
	if in.Type() == nil {
		return NewEtcdBackupValueNull(), nil
	}

	if !in.Type().Equal(t.TerraformType(ctx)) {
		return nil, fmt.Errorf("expected %s, got %s", t.TerraformType(ctx), in.Type())
	}

	if !in.IsKnown() {
		return NewEtcdBackupValueUnknown(), nil
	}

	if in.IsNull() {
		return NewEtcdBackupValueNull(), nil
	}

	attributes := map[string]attr.Value{}

	val := map[string]tftypes.Value{}

	err := in.As(&val)

	if err != nil {
		return nil, err
	}

	for k, v := range val {
		a, err := t.AttrTypes[k].ValueFromTerraform(ctx, v)

		if err != nil {
			return nil, err
		}

		attributes[k] = a
	}

	return NewEtcdBackupValueMust(EtcdBackupValue{}.AttributeTypes(ctx), attributes), nil
}

func (t EtcdBackupType) ValueType(ctx context.Context) attr.Value {
	return EtcdBackupValue{}
}

var _ basetypes.ObjectValuable = EtcdBackupValue{}

type EtcdBackupValue struct {
	DailyBackupTime         basetypes.StringValue `tfsdk:"daily_backup_time"`
	IntervalInHours         basetypes.Int64Value  `tfsdk:"interval_in_hours"`
	IntervalInMins          basetypes.Int64Value  `tfsdk:"interval_in_mins"`
	IsEtcdBackupEnabled     basetypes.BoolValue   `tfsdk:"is_etcd_backup_enabled"`
	MaxIntervalBackupCount  basetypes.Int64Value  `tfsdk:"max_interval_backup_count"`
	MaxTimestampBackupCount basetypes.Int64Value  `tfsdk:"max_timestamp_backup_count"`
	StorageLocalPath        basetypes.StringValue `tfsdk:"storage_local_path"`
	StorageType             basetypes.StringValue `tfsdk:"storage_type"`
	state                   attr.ValueState
}

func (v EtcdBackupValue) ToTerraformValue(ctx context.Context) (tftypes.Value, error) {
	attrTypes := make(map[string]tftypes.Type, 8)

	var val tftypes.Value
	var err error

	attrTypes["daily_backup_time"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["interval_in_hours"] = basetypes.Int64Type{}.TerraformType(ctx)
	attrTypes["interval_in_mins"] = basetypes.Int64Type{}.TerraformType(ctx)
	attrTypes["is_etcd_backup_enabled"] = basetypes.BoolType{}.TerraformType(ctx)
	attrTypes["max_interval_backup_count"] = basetypes.Int64Type{}.TerraformType(ctx)
	attrTypes["max_timestamp_backup_count"] = basetypes.Int64Type{}.TerraformType(ctx)
	attrTypes["storage_local_path"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["storage_type"] = basetypes.StringType{}.TerraformType(ctx)

	objectType := tftypes.Object{AttributeTypes: attrTypes}

	switch v.state {
	case attr.ValueStateKnown:
		vals := make(map[string]tftypes.Value, 8)

		val, err = v.DailyBackupTime.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["daily_backup_time"] = val

		val, err = v.IntervalInHours.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["interval_in_hours"] = val

		val, err = v.IntervalInMins.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["interval_in_mins"] = val

		val, err = v.IsEtcdBackupEnabled.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["is_etcd_backup_enabled"] = val

		val, err = v.MaxIntervalBackupCount.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["max_interval_backup_count"] = val

		val, err = v.MaxTimestampBackupCount.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["max_timestamp_backup_count"] = val

		val, err = v.StorageLocalPath.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["storage_local_path"] = val

		val, err = v.StorageType.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["storage_type"] = val

		if err := tftypes.ValidateValue(objectType, vals); err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		return tftypes.NewValue(objectType, vals), nil
	case attr.ValueStateNull:
		return tftypes.NewValue(objectType, nil), nil
	case attr.ValueStateUnknown:
		return tftypes.NewValue(objectType, tftypes.UnknownValue), nil
	default:
		panic(fmt.Sprintf("unhandled Object state in ToTerraformValue: %s", v.state))
	}
}

func (v EtcdBackupValue) IsNull() bool {
	return v.state == attr.ValueStateNull
}

func (v EtcdBackupValue) IsUnknown() bool {
	return v.state == attr.ValueStateUnknown
}

func (v EtcdBackupValue) String() string {
	return "EtcdBackupValue"
}

func (v EtcdBackupValue) ToObjectValue(ctx context.Context) (basetypes.ObjectValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	objVal, diags := types.ObjectValue(
		map[string]attr.Type{
			"daily_backup_time":          basetypes.StringType{},
			"interval_in_hours":          basetypes.Int64Type{},
			"interval_in_mins":           basetypes.Int64Type{},
			"is_etcd_backup_enabled":     basetypes.BoolType{},
			"max_interval_backup_count":  basetypes.Int64Type{},
			"max_timestamp_backup_count": basetypes.Int64Type{},
			"storage_local_path":         basetypes.StringType{},
			"storage_type":               basetypes.StringType{},
		},
		map[string]attr.Value{
			"daily_backup_time":          v.DailyBackupTime,
			"interval_in_hours":          v.IntervalInHours,
			"interval_in_mins":           v.IntervalInMins,
			"is_etcd_backup_enabled":     v.IsEtcdBackupEnabled,
			"max_interval_backup_count":  v.MaxIntervalBackupCount,
			"max_timestamp_backup_count": v.MaxTimestampBackupCount,
			"storage_local_path":         v.StorageLocalPath,
			"storage_type":               v.StorageType,
		})

	return objVal, diags
}

func (v EtcdBackupValue) Equal(o attr.Value) bool {
	other, ok := o.(EtcdBackupValue)

	if !ok {
		return false
	}

	if v.state != other.state {
		return false
	}

	if v.state != attr.ValueStateKnown {
		return true
	}

	if !v.DailyBackupTime.Equal(other.DailyBackupTime) {
		return false
	}

	if !v.IntervalInHours.Equal(other.IntervalInHours) {
		return false
	}

	if !v.IntervalInMins.Equal(other.IntervalInMins) {
		return false
	}

	if !v.IsEtcdBackupEnabled.Equal(other.IsEtcdBackupEnabled) {
		return false
	}

	if !v.MaxIntervalBackupCount.Equal(other.MaxIntervalBackupCount) {
		return false
	}

	if !v.MaxTimestampBackupCount.Equal(other.MaxTimestampBackupCount) {
		return false
	}

	if !v.StorageLocalPath.Equal(other.StorageLocalPath) {
		return false
	}

	if !v.StorageType.Equal(other.StorageType) {
		return false
	}

	return true
}

func (v EtcdBackupValue) Type(ctx context.Context) attr.Type {
	return EtcdBackupType{
		basetypes.ObjectType{
			AttrTypes: v.AttributeTypes(ctx),
		},
	}
}

func (v EtcdBackupValue) AttributeTypes(ctx context.Context) map[string]attr.Type {
	return map[string]attr.Type{
		"daily_backup_time":          basetypes.StringType{},
		"interval_in_hours":          basetypes.Int64Type{},
		"interval_in_mins":           basetypes.Int64Type{},
		"is_etcd_backup_enabled":     basetypes.BoolType{},
		"max_interval_backup_count":  basetypes.Int64Type{},
		"max_timestamp_backup_count": basetypes.Int64Type{},
		"storage_local_path":         basetypes.StringType{},
		"storage_type":               basetypes.StringType{},
	}
}
