// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package datasource_nodes

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
)

func NodesDataSourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"api_responding": schema.Int64Attribute{
				Computed:            true,
				Description:         "1 indicates the API server on this node is running. 0 otherwise. Applicable only if isMaster is 1",
				MarkdownDescription: "1 indicates the API server on this node is running. 0 otherwise. Applicable only if isMaster is 1",
			},
			"cloud_provider_type": schema.StringAttribute{
				Computed:            true,
				Description:         "Type of cloud provider, such as local or aws used to create the cluster",
				MarkdownDescription: "Type of cloud provider, such as local or aws used to create the cluster",
			},
			"cluster_name": schema.StringAttribute{
				Computed:            true,
				Description:         "Name of the cluster the node belongs to",
				MarkdownDescription: "Name of the cluster the node belongs to",
			},
			"cluster_uuid": schema.StringAttribute{
				Computed:            true,
				Description:         "UUID of the cluster the node belongs to",
				MarkdownDescription: "UUID of the cluster the node belongs to",
			},
			"id": schema.StringAttribute{
				Required:            true,
				Description:         "UUID of the cluster",
				MarkdownDescription: "UUID of the cluster",
			},
			"is_master": schema.Int64Attribute{
				Computed:            true,
				Description:         "1 if this node is a master of a custer. 0 otherwise.",
				MarkdownDescription: "1 if this node is a master of a custer. 0 otherwise.",
			},
			"name": schema.StringAttribute{
				Computed:            true,
				Description:         "Host name of the node",
				MarkdownDescription: "Host name of the node",
			},
			"node_pool_name": schema.StringAttribute{
				Computed:            true,
				Description:         "Name of the node pool, the node belongs to",
				MarkdownDescription: "Name of the node pool, the node belongs to",
			},
			"node_pool_uuid": schema.StringAttribute{
				Computed:            true,
				Description:         "UUID of the node pool, the node belongs to",
				MarkdownDescription: "UUID of the node pool, the node belongs to",
			},
			"primary_ip": schema.StringAttribute{
				Computed:            true,
				Description:         "IP address of the node",
				MarkdownDescription: "IP address of the node",
			},
			"project_id": schema.StringAttribute{
				Required:            true,
				Description:         "UUID of the project the cluster belongs to",
				MarkdownDescription: "UUID of the project the cluster belongs to",
			},
			"status": schema.StringAttribute{
				Computed:            true,
				Description:         "Status of the node. States include “ok”, ”converging”, “failed”. These states indicate the current state of kubernetes setup on the host.",
				MarkdownDescription: "Status of the node. States include “ok”, ”converging”, “failed”. These states indicate the current state of kubernetes setup on the host.",
			},
			"uuid": schema.StringAttribute{
				Computed:            true,
				Description:         "UUID of the node",
				MarkdownDescription: "UUID of the node",
			},
		},
	}
}

type NodesModel struct {
	ApiResponding     types.Int64  `tfsdk:"api_responding"`
	CloudProviderType types.String `tfsdk:"cloud_provider_type"`
	ClusterName       types.String `tfsdk:"cluster_name"`
	ClusterUuid       types.String `tfsdk:"cluster_uuid"`
	Id                types.String `tfsdk:"id"`
	IsMaster          types.Int64  `tfsdk:"is_master"`
	Name              types.String `tfsdk:"name"`
	NodePoolName      types.String `tfsdk:"node_pool_name"`
	NodePoolUuid      types.String `tfsdk:"node_pool_uuid"`
	PrimaryIp         types.String `tfsdk:"primary_ip"`
	ProjectId         types.String `tfsdk:"project_id"`
	Status            types.String `tfsdk:"status"`
	Uuid              types.String `tfsdk:"uuid"`
}
