// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package provider_pf9

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework/provider/schema"
)

func Pf9ProviderSchema(ctx context.Context) schema.Schema {
	return schema.Schema{}
}

type Pf9Model struct {
}
