// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package datasource_cluster

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
)

func ClusterDataSourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"id": schema.StringAttribute{
				Required:            true,
				Description:         "UUID of the cluster",
				MarkdownDescription: "UUID of the cluster",
			},
			"kubeconfig": schema.StringAttribute{
				Computed:            true,
				Description:         "Kubeconfig blob",
				MarkdownDescription: "Kubeconfig blob",
			},
			"master_status": schema.StringAttribute{
				Computed:            true,
				Description:         "Master status",
				MarkdownDescription: "Master status",
			},
			"name": schema.StringAttribute{
				Computed:            true,
				Description:         "Name of the cluster",
				MarkdownDescription: "Name of the cluster",
			},
			"project_id": schema.StringAttribute{
				Computed:            true,
				Description:         "UUID of the project the cluster belongs to",
				MarkdownDescription: "UUID of the project the cluster belongs to",
			},
			"status": schema.StringAttribute{
				Computed:            true,
				Description:         "Status",
				MarkdownDescription: "Status",
			},
			"task_error": schema.StringAttribute{
				Computed:            true,
				Description:         "Error during execution of task",
				MarkdownDescription: "Error during execution of task",
			},
			"task_status": schema.StringAttribute{
				Computed:            true,
				Description:         "Status of task execution",
				MarkdownDescription: "Status of task execution",
			},
			"worker_status": schema.StringAttribute{
				Computed:            true,
				Description:         "Worker status",
				MarkdownDescription: "Worker status",
			},
		},
	}
}

type ClusterModel struct {
	Id           types.String `tfsdk:"id"`
	Kubeconfig   types.String `tfsdk:"kubeconfig"`
	MasterStatus types.String `tfsdk:"master_status"`
	Name         types.String `tfsdk:"name"`
	ProjectId    types.String `tfsdk:"project_id"`
	Status       types.String `tfsdk:"status"`
	TaskError    types.String `tfsdk:"task_error"`
	TaskStatus   types.String `tfsdk:"task_status"`
	WorkerStatus types.String `tfsdk:"worker_status"`
}
